name: Tests CI
on: [push, workflow_dispatch]
jobs:
  static-elsint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
  unit-integration-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run jest
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
  ui-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          build: npm run generate
          start: npm run start
          wait-on: 'http://localhost:3000'
      - name: Percy Test
        run: npx percy exec -- cypress run --browser chrome --headless --env percy=treu,grep=visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
